# I pledge my honor that I have abided by the Stevens Honor System - atartagl

CC = gcc
OBJS = cs392_thread.o

cs392_thread: $(OBJS)
	$(CC) -pthread -o cs392_thread cs392_thread.o

clean:
	rm -rf *.o cs392_thread

